# === Stage 53: Add command help text and usage examples ===
# Project: VolunteerDesk
def show_help():
    """Print usage information and examples for VolunteerDesk."""
    print("\nVolunteerDesk - Volunteer Coordination System")
    print("=" * 40)
    print("Available Commands:")
    print("  list_shifts          - Show all scheduled shifts")
    print("  sign_up              - Sign up for a shift")
    print("  view_hours           - View logged hours")
    print("  add_note             - Add a thank-you note")
    print("  help                 - Show this help message")
    print()
    print("Usage Examples:")
    print("  >> list_shifts")
    print("  >> sign_up")
    print("  >> view_hours")
    print("  >> add_note")
    print("  >> help")
    print()
    print("Example interactions:")
    print("  Volunteer: I want to help tomorrow.")
    print("  System: Available shifts are listed.")
    print("  Volunteer: I'll sign up for the morning shift.")
    print("  System: You are signed up successfully.")
    print("  Volunteer: How many hours have I logged?")
    print("  System: Your total hours are displayed.")
    print("  Volunteer: I'd like to thank a volunteer.")
    print("  System: Your thank-you note has been added.")
